### ISSUE TITLE
Implementation does not support hiding existing BindableProperties

### ISSUE THREAD

**Issue by IndianaGary** [rrmanzano/maui-bindableproperty-generator#1]
I have several controls where I mask the underlying property with my own.

For example:

BackgroundColor is implemented by VisualElement, but I want to provide my own and 
the BottomDrawer control inherits from ContentView which descends from VisualElement.
To implement the property I do the following:

```
public static new readonly BindableProperty BackgroundColorProperty =
                           BindableProperty.Create(nameof(BackgroundColor),
                                                   typeof(Color),
                                                   typeof(BottomDrawer),
                                                   Colors.White );
public new Color BackgroundColor
{
    get => (Color)GetValue( BackgroundColorProperty );
    set => SetValue( BackgroundColorProperty, value );
}
```
As you can see, hiding the underlying property requires adding the "new" keyword.

Recommendation:

Add a named argument such as "HidesUnderlyingProperty" with a default of "false". If the user
sets it to "true", then insert "new" in the appropriate locations.

I can open a separate issue if you prefer, but I would also recommend formating the Create call
to be much more readable than it is now.

**Comment by rrmanzano** [comment]
First of all thank you for your feedback, I am always open to comments and thanks for detailing the example, I like your proposal/recommendation, I will probably include it in the next release, thanks.

**Comment by IndianaGary** [comment]
I'm just getting started. 🤣 I was planning to implement this myself, but you beat me to it.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by rrmanzano** [comment]
Hi @IndianaGary , I just sent a new release (Version 0.6.0) that includes the new functionality to hide existing BindableProperties. Here the [example](https://github.com/rrmanzano/maui-bindableproperty-generator#usage---hide-existing-bindableproperties).

Regarding your comment "formating the Create call to be much more readable than it is now", I going to include that change in the next release (Version 0.7.0). Thanks

**Comment by rrmanzano** [comment]
Hi @IndianaGary, a new version (0.7.0) is ready, now the library is generating code more readable, you can see the examples in the readme file (I already updated all the examples with the new format). I going to close this issue, thank you for your feedback.

**Comment by IndianaGary** [comment]
Great! I'll be trying it out on a Maui BottomDrawer control that I'm writing. It's like a popup except it comes up from the bottom of the device and descends when closed. I wrote it originally for Xamarin Forms and I'm porting it to Maui.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
