### ISSUE TITLE
Partial method call for OnChange

### ISSUE THREAD

**Issue by paulvarache** [rrmanzano/maui-bindableproperty-generator#12]
The MVVM Community Toolkit has a source generator for Observable properties that offers a similar experience to this plugin.

It did add a neat feature recently that I would love to have in this plugin. The generator defines a partial method for each property with the attribute, leaving the developer the option to implement said partial method to react to property changes. This is the type of experience you get in Visual Studio:

![image](https://user-images.githubusercontent.com/5550089/233312139-658aeef6-3d01-4959-8296-b580df03eaa6.png)

Currently the `OnChange` property in the Attribute options requires this syntax:

```cs
[AutoBindable(OnChange = nameof(OnMyPropertyChanged))]
readonly int _myProperty;

void OnMyPropertyChanged() {}
```

With partial methods calls generated, it would looks like this:

```cs
[AutoBindable]
readonly int _myProperty;

partial void OnMyPropertyChanged(int value) {}
partial void OnMyPropertyChanging(int value) {}
```

I would also envision adding the `changing` variant of the property change event.

Pros:

 - Less config to react to property changes
 - Less verbose way of supporting changing event
 - Better discoverability in editor (Simply typing partial lists all the available partial methods)
 - Not relying on a string for the method name (And having to use nameof)
 - Aligns with the MVVM community toolkit's implementation, that would hopefully lead to an easier adoption of this plugin

Cons:
 - Does not allow customising the names of the methods

**Comment by rrmanzano** [comment]
This new feature was published in version 0.11.0, Thanks @paulvarache for your great contribution.
https://github.com/rrmanzano/maui-bindableproperty-generator/releases/tag/0.11.0
