### ISSUE TITLE
Add License Information for Commercial Project Usage

### ISSUE THREAD

**Issue by BAL4-R** [rrmanzano/maui-bindableproperty-generator#15]
I would like to use this package in a project, However, I noticed the absence of license information in the repository. 
Kindly consider adding license details to clarify the terms of usage for commercial purposes.

**Comment by rrmanzano** [comment]
Hi @BAL4-R , the license is MIT, I will include the license file in the next release, probably in the next 24 hours. Thanks

**Comment by rrmanzano** [comment]
The license was published in the latest version, Thanks @BAL4-R 
https://github.com/rrmanzano/maui-bindableproperty-generator/releases/tag/0.11.0
