### ISSUE TITLE
The call is ambiguous when updating from 0.10 to 0.11

### ISSUE THREAD

**Issue by micke-inor** [rrmanzano/maui-bindableproperty-generator#16]
When updating from 0.10 to 0.11 from the NuGet package i get this error.

**CS0121: The call is ambiguous between the following methods or properties: 'AutoBindableAttribute.AutoBindableAttribute(y and 'AutoBindableAttribute.AutoBindableAttribute(y** 

If I downgrade down to 0.10 the error disappear again.

I am using .NET MAUI (.net 7) and Visual Studio 17.6.4 on Windows 10.0.19045.2486

How to reproduce:
* Create new .net MAUI project in VS2022
* Add NuGet M.BindableProperty.Generator
* Change MainPage.xaml.cs to add one AutoBindable

```
namespace MauiApp1;

public partial class MainPage : ContentPage
{

    [AutoBindable]
    private readonly string _placeholder;


    int count = 0;

	public MainPage()
	{
		InitializeComponent();
	}

	private void OnCounterClicked(object sender, EventArgs e)
	{
		count++;

		if (count == 1)
			CounterBtn.Text = $"Clicked {count} time";
		else
			CounterBtn.Text = $"Clicked {count} times";

		SemanticScreenReader.Announce(CounterBtn.Text);
	}
}
```

**Comment by SebiHebo** [comment]
We are having the same issue, when updating to 0.11.

**Comment by rrmanzano** [comment]
Hi @SebiHebo and @micke-inor thanks for your feedback, I can confirm there is an issue in the latest version, I going to send a hotfix in the following hours

**Comment by SebiHebo** [comment]
Can confirm, it is working for us now on Version v0.11.1 Thanks for the quick fix!
