### ISSUE TITLE
Doesnt work with generic classes

### ISSUE THREAD

**Issue by kofanov** [rrmanzano/maui-bindableproperty-generator#5]
Hello! Thank you for the great generator!
Unfortunately it doesnt work with generic classes.

Example:

public partial class GenericClass&lt;T&gt;
{
    [AutoBindable] bool _isGenerated;

    public GenericClass()
    {
        IsGenerated = false; // The name "IsGenerated" Does not exist in the current context
    }
}

**Comment by rrmanzano** [comment]
First of all, thank you for your feedback @kofanov , I am always open to comments. I can confirm there is an issue with generics, I will work on this fix ASAP, thanks.

**Comment by rrmanzano** [comment]
Hi @kofanov, the fix is ready, you can use the new version 0.9.2, and again, thanks for your feedback !!

Nuget:
https://www.nuget.org/packages/M.BindableProperty.Generator/0.9.2

Commit:
https://github.com/rrmanzano/maui-bindableproperty-generator/commit/3ac5cfdd46f3b3a27164cb40d66fd328a910329c
