### ISSUE TITLE
Need add AttributesProperty

### ISSUE THREAD

**Issue by yiszza** [rrmanzano/maui-bindableproperty-generator#6]
[AutoBindable(AttributesProperty= "[EditorBrowsable(EditorBrowsableState.Never)], [TypeConverter(typeof(valueConverter))]")]
bool isValue

to

[EditorBrowsable(EditorBrowsableState.Never)]
[TypeConverter(typeof(valueConverter))]
public bool IsValue
{
    get => (bool)GetValue(IsValueProperty);
    set => SetValue(IsValueProperty, value);
}

**Comment by rrmanzano** [comment]
Hi @yiszza thank you for your feedback, that is a very good feature, I will include this functionality in the next release
