### ISSUE TITLE
Only Support public class

### ISSUE THREAD

**Issue by yiszza** [rrmanzano/maui-bindableproperty-generator#8]
![image](https://user-images.githubusercontent.com/42995476/209313022-3baf476b-c3a7-4af5-a704-fa378b42e248.png)
CS0262: Partial declarations of 'type' have conflicting accessibility modifiers
Some time, we need create a internal view

thank you!

**Comment by rrmanzano** [comment]
Hi, @yiszza thank you for your feedback. I will take a look and send the fix soon.

**Comment by rrmanzano** [comment]
Hi @yiszza, I just sent a new version that includes this new functionality, please check the section "PropertyAccessibility". Thanks again for your feedback.

Here is the section:
https://github.com/rrmanzano/maui-bindableproperty-generator#usage---propertyaccessibility

Here is the new version:
https://github.com/rrmanzano/maui-bindableproperty-generator/releases/tag/0.10.0
